### ISSUE TITLE
How to use wLE interface to play PS2 games with Neutrino

### ISSUE THREAD

**Issue by Thad-Supersperm** [rickgaiser/neutrino#7]
I'd like to know how to use Neutrino and wLE to play PS2 games, to be able to browse the internal HDD and maybe be able to sort games in folders according to the first letter of the title.

**Comment by rickgaiser** [comment]
That's not possible.

Neutrino is a command line tool only (a backend).
What you are looking for is a frontend / UI / GUI. Everyone can create their own for neutrino. Currently only 1 exists, a plugin for XEB+.

**Comment by Phantasm90** [comment]
> Currently only 1 exists, a plugin for XEB+.

Is there a way to play via UDPBD on XEB+?

**Comment by Andre-Cardozo-Web** [comment]
Neutrino GSM
When trying to use GSM - Graphics synthesizer mode selector before opening the game through the Neutrino Plugin - I get a static black screen - I do this by using a separate GSM ELF before opening +XEB - Since I can only open Neutrino at the moment through +XEB - +XEB itself does not open and crashes on the black screen - So I do not know if Neutrino is compatible with opening GSM before it - When trying to use the GSM plugin within the +XEB interface itself I also get a black screen - Will Neutrino be compatible with GSM in the future? - If so, how will I go about getting through the +XEB interface? - Thanks

**Comment by rickgaiser** [comment]
I think it only supports USB, but don't know. You can ask the developers of XEB+.
